### ISSUE TITLE
Working example for pull to refresh functionality

### ISSUE THREAD

**Issue by KKS1** [mgcrea/angular-pull-to-refresh#1]
Hi,

Could you please add a working example utilizing the pull to refresh directive in the page.

Thanks,
Jeet

**Comment by mgcrea** [comment]
It's in the works

**Comment by KKS1** [comment]
Great, thanks for the update.
Any ETA on this ?

Regards,
Kanwaljeet

**Comment by slowernet** [comment]
+1. Having trouble determining what assumptions the module makes about the style/positioning of the element where it is applied. Thanks.

**Comment by rahuljiresal** [comment]
+1. A working demo would be very much appreciated. Thank you.

**Comment by mgcrea** [comment]
Here is the less source file in my app, I haven't got the time to set up proper docs for this yet, sorry.

``` less
.ptr {
  @height: 20px;
  display: block;
  width: 100%;
  text-align: center;
  position: relative;
  height: @height;
  margin: -2*@height - 1px auto 0;
  padding: @height/2 0;
  -webkit-transition-property: margin;
  -webkit-transition-duration: 400ms;
  border-bottom: 1px dashed #ccc;
  &.ptr-pull {

  }
  &.ptr-release {

  }
  &.ptr-loading {
    margin: 0 auto;
    -webkit-transition-duration: 0ms;
  }
}
```

Hope that will help
